repos:
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
    -   id: pylint-score-limit
        args:
        - --limit=8.5